appName: demo
service: 
  type: ClusterIP
  expose:
  - externalPort:  
    internalPort: 
    type: vpn
  - externalPort:  
    internalPort: 
    type: external
  - externalPort:  
    internalPort: 
    type: internal
ingress:
  exposeName: test
  annotations:
    external:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    internal:
      kubernetes.io/ingress.class: nginx-internal
    vpn:
      kubernetes.io/ingress.class: "nginx-vpn"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 100Mi
kind: Deployment
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 11
  targetCPUUtilizationPercentage: 500
image:
  repository: draft
  tag: dev
  pullPolicy: IfNotPresent
probePath: /status
probePort: 
livenessProbe:
  initialDelaySeconds: 
  periodSeconds: 
  successThreshold: 
  timeoutSeconds: 
readinessProbe:
  periodSeconds: 
  successThreshold: 
  timeoutSeconds: 
terminationGracePeriodSeconds: 
replicaCount: 2
maxSurge: 30%
maxUnavailable: 30%
tolerations:
# nodeSelector:
#   spotinst.io/node-lifecycle: od
# podAnnotations:
#     iam.amazonaws.com/role: role-arn