appName: demo
service: 
  type: ClusterIP
  expose:
  - externalPort:  
    internalPort: 
    type: external
  - externalPort:  
    internalPort: 
    type: internal
ingress:
  exposeName: test
  annotations:
    external:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    internal:
      kubernetes.io/ingress.class: nginx-internal
resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 100Mi
kind: Deployment
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 11
  targetCPUUtilizationPercentage: 500
image:
  repository: draft
  tag: dev
probePath: /status
probePort: 
replicaCount: 2
tolerations:
# nodeSelector:
#   spotinst.io/node-lifecycle: od
# podAnnotations:
#     iam.amazonaws.com/role: role-arn
