apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: app-name
  namespace: app-ns
  annotations:
    artifact.spinnaker.io/location: app-ns
    artifact.spinnaker.io/name: app-name
    artifact.spinnaker.io/type: kubernetes/horizontalpodautoscaler
    moniker.spinnaker.io/application: app-name
    moniker.spinnaker.io/cluster: "horizontalpodautoscaler app-name"
  labels:
    app: app-name
    app.kubernetes.io/managed-by: spinnaker
    app.kubernetes.io/name: app-name
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: app-name
  minReplicas: 1
  maxReplicas: 11
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 400
